### ISSUE TITLE
How can I achieve this kind of exception logic?

### ISSUE THREAD

**Issue by aquinary** [dart-lang/stack_trace#158]
I'm trying to achieve more concise output about exceptions in my library.
I want to provide the user with the ability to catch errors like this:

First example:
```dart
void main() {
  try {
    final response = await db.execute('SELECT * FROM items');
  } on TarantoolNoSuchSpaceException {
    // Any code, no exception should be thrown here.
  } on TarantoolAnotherException {
    // There may be many such exceptions.
  }
}
```

Second example:
```dart
void main() {
  // The exception should be caught here and pretty formatting.
  final response = await db.execute('SELECT * FROM items');
}
```

When I use Chain.capture, I ALWAYS throw an exception, even when I catch it as in the first example.
I'd like to work with exceptions the same way we usually work with them. But at the same time get pretty formatting.
I'd like to implement all the logic associated with `stack_trace` inside my library so that the user doesn't have to think about it.
Is this possible?

**Comment by osa1** [comment]
> I'd like to work with exceptions the same way we usually work with them. But at the same time get pretty formatting.

The way you usually work with stack traces are:

1. In `catch` blocks: `catch (e, st) { ... }` here `st` is the stack trace of the `throw` that throws the exception caught.
2. Using `Error.stackTrace` member.

You can have your own `StackTrace` class that prints in the format you prefer:

```dart
class MyStackTrace implements StackTrace {
  ...

  @override
  String toString() {
    ...
  }
}
```

However you don't have control over the stack trace value when using `throw`, so you can't use values of this type in (1).

In (2) you can have your own errors that use your stack trace class:

```dart
class MyError implements Error {
  ...

  @override
  MyStackTrace get stackTrace => ...;
}
```

But it seems like you are using exceptions, which don't have a `stackTrace` member, and also your users will probably catch your exceptions with `catch (e, st)` and use `st` instead of `e.stackTrace`.

You can add a member to your exceptions `MyStackTrace get prettyStackTrace` and ask the users to use that.

Hope this helps. Closing as this is not an issue.
